
# Write Kubernetes Deployment Script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book_catalog_deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: book_catalog
  template:
    metadata:
      labels:
        app: book_catalog
    spec:
      containers:
      - name: book_catalog
        image: s223183139/book_catalog:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: book_catalog_service
spec:
  type: NodePort
  selector:
    app: book_catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007
